spring:
  application:
    name: ssuai
  profiles:
    default: dev
  ai:
    mcp:
      server:
        name: ssuai-mcp
        version: 0.0.1
        type: SYNC

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: never

ssuai:
  connector:
    meal: mock # mock | real
    dorm-meal: mock # mock | real
