spring:
  application:
    name: ssuai
  profiles:
    default: dev
  ai:
    mcp:
      server:
        name: ssuai-mcp
        version: 0.0.1
        type: SYNC

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: never

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

ssuai:
  connector:
    meal: mock # mock | real
    dorm-meal: mock # mock | real
